<?php

$DB_HOST = getenv('OPENSHIFT_MYSQL_DB_HOST');
$DB_NAME = 'phoenix'; 
$DB_USERNAME = getenv('OPENSHIFT_MYSQL_DB_USERNAME');
$DB_PASSWORD = getenv('OPENSHIFT_MYSQL_DB_PASSWORD');
$DB_PORT = getenv('OPENSHIFT_MYSQL_DB_PORT'); 

$CRYPTO_KEY = '5&BoAVKn3r6rA84z12TK';
$CRYPTO_METHOD = 'aes-256-cbc';

?>