local _TBL_COUNTRIES = {
	{"Z4", "countryNone", "countryNone"},
	{"AX", "AAland Islands", "Åland"},
	{"AF", "Afghanistan", "افغانستان"},
	{"AL", "Albania", "Shqipëria"},
	{"DZ", "Algeria", "الجزائر"},
	{"AS", "American Samoa", "Amerika Sāmoa"},
	{"AD", "Andorra", "Andorra"},
	{"AO", "Angola", "Angola"},
	{"AI", "Anguilla", "Anguilla"},
	{"AQ", "Antarctic", "Antarctic"},
	{"AG", "Antigua and Barbuda", "Antigua and Barbuda"},
	{"AR", "Argentina", "Argentina"},
	{"AM", "Armenia", "Հայաստան"},
	{"AW", "Aruba", "Aruba"},
	{"AU", "Australia", "Australia"},
	{"AT", "Austria", "Österreich"},
	{"AZ", "Azerbaijan", "Azərbaycan"},
	{"BS", "Bahamas, The", "Bahamas"},
	{"BH", "Bahrain", "البحرين"},
	{"BD", "Bangladesh", "বাংলাদেশ"},
	{"BB", "Barbados", "Barbados"},
	{"BY", "Belarus", "Беларусь"},
	{"BE", "Belgium", "Belgique"},
	{"BZ", "Belize", "Belize"},
	{"BJ", "Benin", "Bénin"},
	{"BM", "Bermuda", "Bermuda"},
	{"BT", "Bhutan", "Druk Yul"},
	{"BO", "Bolivia", "Bolivia"},
	{"BA", "Bosnia and Herzegovina", "Босна и Херцеговина"},
	{"BW", "Botswana", "Botswana"},
	{"BV", "Bouvet Island", "Bouvetøy"},
	{"BR", "Brazil", "Brasil"},
	{"IO", "British Indian Ocean Territory", "British Indian Ocean Territory"},
	{"BN", "Brunei", "Brunei"},
	{"BG", "Bulgaria", "България"},
	{"BF", "Burkina Faso", "Burkina Faso"},
	{"MM", "Burma", "Myanmar"},
	{"BI", "Burundi", "Burundi"},
	{"KH", "Cambodia", "កម្ពុជា"},
	{"CM", "Cameroon", "Cameroon"},
	{"CA", "Canada", "Canada"},
	{"CV", "Cape Verde", "Cabo Verde"},
	{"BQ", "Caribbean Netherlands", "Caribisch Nederland"},
	{"KY", "Cayman Islands", "Cayman Islands"},
	{"CF", "Central African Republic", "Ködörösêse tî Bêafrîka"},
	{"TD", "Chad", "تشاد"},
	{"CL", "Chile", "Chile"},
	{"CN", "China", "中國"},
	{"CX", "Christmas Island", "Christmas Island"},
	{"CC", "Cocos Islands", "Cocos Islands"},
	{"CO", "Colombia", "Colombia"},
	{"KM", "Comoros", "جزر القمر"},
	{"CD", "Congo, Democratic Republic of the", "République démocratique du Congo"},
	{"CG", "Congo, Republic of the", "République du Congo"},
	{"CK", "Cook Islands", "Cook Islands"},
	{"CR", "Costa Rica", "Costa Rica"},
	{"CI", "Côte d'Ivoire", "Côte d'Ivoire"},
	{"HR", "Croatia", "Hrvatska"},
	{"CU", "Cuba", "Cuba"},
	{"CW", "Curaçao", "Curaçao"},
	{"CY", "Cyprus", "Κύπρος"},
	{"CZ", "Czech Republic", "Česká republika"},
	{"DK", "Denmark", "Danmark"},
	{"DJ", "Djibouti", "جيبوتي"},
	{"DM", "Dominica", "Dominica"},
	{"DO", "Dominican Republic", "República Dominicana"},
	{"TL", "East Timor", "Timor-Leste"},
	{"EC", "Ecuador", "Ecuador"},
	{"EG", "Egypt", "مصر"},
	{"SV", "El Salvador", "El Salvador"},
	{"Z1", "England", "England"},
	{"GQ", "Equatorial Guinea", "Guinea Ecuatorial"},
	{"ER", "Eritrea", "إرتريا"},
	{"EE", "Estonia", "Eesti"},
	{"ET", "Ethiopia", "Ethiopia"},
	{"FK", "Falkland Islands", "Falkland Islands"},
	{"FO", "Faroe Islands", "Føroyar"},
	{"FJ", "Fiji", "Fiji"},
	{"FI", "Finland", "Finland"},
	{"FR", "France", "France"},
	{"TF", "French Southern Antarctic Lands", "Terres australes antarctiques françaises"},
	{"GA", "Gabon", "Gabon"},
	{"GM", "Gambia", "Gambia"},
	{"GE", "Georgia", "საქართველო"},
	{"DE", "Germany", "Deutschland"},
	{"GH", "Ghana", "Ghana"},
	{"GI", "Gibraltar", "Gibraltar"},
	{"GR", "Greece", "Ελλάς"},
	{"GL", "Greenland", "Kalaallit Nunaat"},
	{"GD", "Grenada", "Grenada"},
	{"GU", "Guam", "Guåhån"},
	{"GT", "Guatemala", "Guatemala"},
	{"GG", "Guernsey", "Guernsey"},
	{"GF", "Guiana, French", "Guyane"},
	{"GW", "Guinea-Bissau", "Guinea-Bissau"},
	{"GN", "Guinea", "Guinée"},
	{"GY", "Guyana", "Guyana"},
	{"HT", "Haiti", "Haïti"},
	{"HM", "Heard Island and McDonald Islands", "HIMI"},
	{"HN", "Honduras", "Honduras"},
	{"HK", "Hong Kong", "香港"},
	{"HU", "Hungary", "Magyarország"},
	{"IS", "Iceland", "Ísland"},
	{"IN", "India", "Bhārat "},
	{"ID", "Indonesia", "Indonesia"},
	{"IR", "Iran", "ایران"},
	{"IQ", "Iraq", "العراق"},
	{"IE", "Ireland", "Éire"},
	{"IM", "Isle of Man", "Isle of Man"},
	{"IL", "Israel", "إسرائيل"},
	{"IT", "Italy", "Italia"},
	{"JM", "Jamaica", "Jamaica"},
	{"JP", "Japan", "日本"},
	{"JE", "Jersey", "Jersey"},
	{"JO", "Jordan", "الأردن"},
	{"KZ", "Kazakhstan", "Қазақстан"},
	{"KE", "Kenya", "Kenya"},
	{"KI", "Kiribati", "Kiribati"},
	{"KP", "Korea, North", "조선 / 朝鮮"},
	{"KR", "Korea, South", "한국 / 韓國"},
	{"XK", "Kosovo", "Косово"},
	{"KW", "Kuwait", "الكويت"},
	{"KG", "Kyrgyzstan", "Кыргызстан"},
	{"LA", "Laos", "ປະເທດລາວ"},
	{"LV", "Latvia", "Latvija"},
	{"LB", "Lebanon", "لبنان"},
	{"LS", "Lesotho", "Lesotho"},
	{"LR", "Liberia", "Liberia"},
	{"LY", "Libya", "ليبيا"},
	{"LI", "Liechtenstein", "Liechtenstein"},
	{"LT", "Lithuania", "Lithuania"},
	{"LU", "Luxembourg", "Lëtzebuerg"},
	{"MO", "Macau", "Macau"},
	{"MK", "Macedonia", "Македонија"},
	{"MG", "Madagascar", "Madagascar"},
	{"MW", "Malawi", "Malawi"},
	{"MY", "Malaysia", "Malaysia"},
	{"MV", "Maldives", "Maldives"},
	{"ML", "Mali", "Mali"},
	{"MT", "Malta", "Malta"},
	{"MH", "Marshall Islands", "Marshall Islands"},
	{"MQ", "Martinique", "Martinique"},
	{"MR", "Mauritania", "موريتانيا"},
	{"MU", "Mauritius", "Maurice"},
	{"YT", "Mayotte", "Mayotte"},
	{"MX", "Mexico", "México"},
	{"MD", "Moldova", "Moldova"},
	{"MC", "Monaco", "Monaco"},
	{"MN", "Mongolia", "Монгол Улс"},
	{"ME", "Montenegro", "Црна Гора"},
	{"MS", "Montserrat", "Montserrat"},
	{"MA", "Morocco", "المغرب"},
	{"MZ", "Mozambique", "Moçambique"},
	{"NA", "Namibia", "Namibia"},
	{"NR", "Nauru", "Naoero"},
	{"NP", "Nepal", "नेपाल"},
	{"NL", "Netherlands", "Nederland"},
	{"NC", "New Caledonia", "Nouvelle-Calédonie"},
	{"NZ", "New Zealand", "Aotearoa"},
	{"NI", "Nicaragua", "Nicaragua"},
	{"NE", "Niger", "Niger"},
	{"NG", "Nigeria", "Nigeria"},
	{"NU", "Niue", "Niuē"},
	{"NF", "Norfolk Island", "Norfolk Island"},
	{"MP", "Northern Mariana Islands", "Northern Mariana Islands"},
	{"NO", "Norway", "Norge"},
	{"OM", "Oman", "عُمان"},
	{"PK", "Pakistan", "پاکستان"},
	{"PW", "Palau", "Belau"},
	{"PS", "Palestinian National Authority", "فلسطين"},
	{"PA", "Panama", "Panamá"},
	{"PG", "Papua New Guinea", "Papua Niugini"},
	{"PY", "Paraguay", "Paraguay"},
	{"PE", "Peru", "Perú"},
	{"PH", "Philippines", "Pilipinas"},
	{"PN", "Pitcairn Islands", "Pitcairn Islands"},
	{"PL", "Poland", "Polska"},
	{"PF", "Polynesia, French", "Polynésie française"},
	{"PT", "Portugal", "Portugal"},
	{"PR", "Puerto Rico", "Puerto Rico"},
	{"QA", "Qatar", "قطر"},
	{"RE", "Réunion", "Réunion"},
	{"RO", "Romania", "România"},
	{"RU", "Russia", "Россия1"},
	{"RW", "Rwanda", "Rwanda"},
	{"BL", "Saint Barthélemy", "Saint-Barthélemy"},
	{"SH", "Saint Helena Ascension Tristan da Cunha", "Saint Helena Ascension Tristan da Cunha"},
	{"KN", "Saint Kitts and Nevis", "Saint Kitts and Nevis"},
	{"LC", "Saint Lucia", "Sainte-Lucie"},
	{"MF", "Saint Martin", "Saint-Martin"},
	{"PM", "Saint Pierre and Miquelon", "Saint-Pierre-et-Miquelon"},
	{"VC", "Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines"},
	{"WS", "Samoa", "Samoa"},
	{"SM", "San Marino", "San Marino"},
	{"ST", "São Tomé and Príncipe", "São Tomé e Príncipe"},
	{"SA", "Saudi Arabia", "المملكة العربية السعودية"},
	{"Z2", "Scotland", "Scotland"},
	{"SN", "Senegal", "Sénégal"},
	{"RS", "Serbia", "Србија"},
	{"SC", "Seychelles", "Sesel"},
	{"SL", "Sierra Leone", "Sierra Leone"},
	{"SG", "Singapore", "新加坡"},
	{"SX", "Sint Maarten", "Sint Maarten"},
	{"SK", "Slovakia", "Slovensko"},
	{"SI", "Slovenia", "Slovenija"},
	{"SB", "Solomon Islands", "Solomon Aelan"},
	{"SO", "Somalia", "الصومال"},
	{"ZA", "South Africa", "South Africa"},
	{"GS", "South Georgia and South Sandwich Islands", "South Georgia and South Sandwich Islands"},
	{"SS", "South Sudan", "South Sudan"},
	{"ES", "Spain", "España"},
	{"LK", "Sri Lanka", "ශ්‍රී ලංකාව"},
	{"SD", "Sudan", "السودان"},
	{"SR", "Suriname", "Suriname"},
	{"SJ", "Svalbard and Jan Mayen", "Svalbard og Jan Mayen"},
	{"SZ", "Swaziland", "Swaziland"},
	{"SE", "Sweden", "Sverige"},
	{"CH", "Switzerland", "Schweiz"},
	{"SY", "Syria", "سورية"},
	{"TW", "Taiwan (Republic of China)", "中華民國"},
	{"TJ", "Tajikistan", "Тоҷикистон"},
	{"TZ", "Tanzania", "Tanzania"},
	{"TH", "Thailand", "เมืองไทย, ประเทศไทย, ราชอาณาจักรไทย"},
	{"CN_54", "Tibet ", "西藏自治区"},
	{"TG", "Togo", "Togo"},
	{"TO", "Tonga", "Tonga"},
	{"TT", "Trinidad and Tobago", "Trinidad and Tobago"},
	{"TN", "Tunisia", "تونس"},
	{"TR", "Turkey", "Türkiye"},
	{"TM", "Turkmenistan", "Türkmenistan"},
	{"TC", "Turks and Caicos Islands", "Turks and Caicos Islands"},
	{"TV", "Tuvalu", "Tuvalu"},
	{"UG", "Uganda", "Uganda"},
	{"UA", "Ukraine", "Україна"},
	{"AE", "United Arab Emirates", "الإمارات العربيّة المتّحدة"},
	{"GB", "United Kingdom", "Britain"},
	{"US", "United States", "United States"},
	{"UY", "Uruguay", "Uruguay"},
	{"UZ", "Uzbekistan", "Ўзбекистон"},
	{"VU", "Vanuatu", "Vanuatu"},
	{"VA", "Vatican City", "Città del Vaticano"},
	{"VE", "Venezuela", "Venezuela"},
	{"VN", "Vietnam", "Việt Nam"},
	{"VG", "Virgin Islands, British", "Virgin Islands, British"},
	{"VI", "Virgin Islands, U.S.", "Virgin Islands, U.S."},
	{"Z3", "Wales", "Cymru "},
	{"WF", "Wallis and Futuna", "Wallis-et-Futuna"},
	{"YE", "Yemen", "اليمن"},
	{"ZM", "Zambia", "Zambia"},
	{"ZW", "Zimbabwe", "Zimbabwe"}
}

local countries ={}

local infFlags = require("classes.infoFlags")
local shtFlags = graphics.newImageSheet("images/ui/scnFlags.png", infFlags:getSheet())

local function anIndexOf(self, value)
	local i = 1
    for i=1, #_TBL_COUNTRIES do 
        if _TBL_COUNTRIES[i][1] == value then return i end
        i = i + 1
    end
    return 1
end

local function getFlag(self, code)
	local i = self:anIndexOf(code)
	return display.newSprite(shtFlags, {{name="standard", start=i, count=1}})
end

local function getCountry(self, code)
	local i = self:anIndexOf(code)
	local country ={
		code=_TBL_COUNTRIES[i][1],
		name=_TBL_COUNTRIES[i][2],
		nameOriginal=_TBL_COUNTRIES[i][3],
		image=display.newSprite(shtFlags, {{name="standard", start=i, count=1}}),
	}
	return country
end

local function getCountryDefault(self)
	local code = system.getPreference("locale","country")
	local i = self:anIndexOf(code)
	if i == 1 then
		local codeAux = string.sub(code, 1, 2)
		if codeAux ~= nil then
			codeAux = codeAux:upper()
		end
		i = self:anIndexOf(codeAux)
	end
	local country ={
			code=_TBL_COUNTRIES[i][1],
			name=_TBL_COUNTRIES[i][2],
			nameOriginal=_TBL_COUNTRIES[i][3],
			image=display.newSprite(shtFlags, {{name="standard", start=i, count=1}}),
	}
	return country
end

local function getAllCountries(self)
	local tblCountries ={}
    for i=1, #_TBL_COUNTRIES do 
		tblCountries[i] ={
			code=_TBL_COUNTRIES[i][1],
			name=_TBL_COUNTRIES[i][2],
			nameOriginal=_TBL_COUNTRIES[i][3],
			image=display.newSprite(shtFlags, {{name="standard", start=i, count=1}}),
		}
    end
    return tblCountries
end

countries.anIndexOf = anIndexOf
countries.getFlag = getFlag
countries.getCountry = getCountry
countries.getCountryDefault = getCountryDefault
countries.getAllCountries = getAllCountries

return countries